### ISSUE TITLE
test_shape_values broken - set up CI?

### ISSUE THREAD

**Issue by kimauth** [kimauth/GPU_computing_tracks_course#4]
`test_shape_values` is broken because of https://github.com/kimauth/GPU_computing_tracks_course/blame/29fb4fcd0106d37eb66815c68755710e8fd9047f/BasicFEM/weak_form.py#L74 . Please always run the unit tests before merging, this would have been detected by them. Would be nice to set up a CI running tests on each PR to avoid this type of problem in the future.

**Comment by ribesstefano** [comment]
Looking around, one free option for automatic CI could be to use [CircleCI](https://circleci.com/docs/getting-started/). Shall I add it to the repo and configure it accordingly?

Unfortunately, there seems to be [no free CI system for testing on GPUs](https://groups.google.com/g/cupy/c/Gsrs4Ojx54I). So for that, we'll have to rely on our local and Chalmers' machines.

**Comment by ribesstefano** [comment]
Since our repository is open, we can actually leverage [Github Actions](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) and use them. What do you think?

**Comment by kimauth** [comment]
Github Actions sounds great, I'm using that for Julia projects too! Free GPU testing seems to be indeed not easily available, but CPU testing for making sure the FEM code is still correct would be a good start. 🙂

**Comment by ribesstefano** [comment]
I've setup an Action, but the unit tests now fail for some dependency issue on `pygmsh`.  Sorry for the commit spam, I'll investigate the problem later tonight.

**Comment by kimauth** [comment]
🎉
